SQLALCHEMY_DATABASE_URI = 'postgresql://someone:someone@localhost/test'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECURITY_PASSWORD_HASH = 'pbkdf2_sha512'
SECURITY_TRACKABLE = True
SECRET_KEY = ''
SECURITY_PASSWORD_SALT = ''
WTF_CSRF_ENABLED = False
BASE_URL=''
DEFAULTHGRAPH="<http://localhost:8890/test>"
VIRTUOSO_USER=''
VIRTUOSO_PASS=''
LOCAL_SPARQL='http://localhost:8890/sparql'
UNIPROT_SPARQL='http://sparql.uniprot.org/sparql'
